source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'

gem 'rails', '~> 7.0.8'
gem 'bootsnap', require: false
gem 'shopify_app'
gem 'shopify_api'
gem 'httparty'
gem 'dotenv-rails'
gem 'cors'

group :development, :test do
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem 'rack-cors'
end
